name: Format Test

on: [push]

jobs:
  format-test:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: install-clang-format
      run: brew install clang-format
    - name: clang-format
      run: |
        clang-format src/*.cpp include/elasty/*.hpp tests/*.*pp examples/**/*.*pp --output-replacements-xml | grep -c "<replacement " >/dev/null
        if [ $? -ne 1 ]; then
          echo "Ill-styled code detected"
          exit 1
        fi
